### PR TITLE
Update deprecated link to airbnb javascript styling

### PR DESCRIPTION
**Pull request by cameronblandford**
Should this link to the readme or to the main page of the repo?

### CODE REVIEW

**Comment by cameronblandford** [comment]
Should this link to the readme or to the main page of the repo?

**Comment by mfraezz** [comment]
>Should this link to the readme or to the main page of the repo?

This should probably actually point the now-deprecated [ES5 guide](https://github.com/airbnb/javascript/tree/es5-deprecated/es5), which is what was previously being linked to. We don't currently support ES6 syntax, mostly because of browser support.

**Comment by cameronblandford** [comment]
> This should probably actually point the now-deprecated ES5 guide,


Done and done.

**Comment by sloria** [comment]
Thanks!

**Pull request merged**
